function  data=txy_importer(filepath,filenum_str)
%this function imports txy files faster by using strongly a matched import
%double precision
%simply pass the filepath and file number (as string)

fileID = fopen([filepath,'_txy_forc',filenum_str,'.txt'],'r');
data = textscan(fileID,'%f64%f64%f64',...%f32
    'Delimiter', ',', ...
    'MultipleDelimsAsOne',0,...
    'ReturnOnError', true,...
    'NumCharactersToSkip',0,... 
    'CollectOutput', true,...
    'EndOfLine','\n');
fclose(fileID);
data=data{1};
end
